version: '3'
services:
    stack_bof_freertos:
        container_name: stack_bof_freertos
        build:
            context: .
            args:
              - proj=/toys/stack_bof
            dockerfile: ./Dockerfile
        ports:
            - 1234:1234
